//
//  GPCatalog.m
//  GonePostal
//
//  Created by Travis Gruber on 8/4/13.
//  Copyright (c) 2013 Travis Gruber. All rights reserved.
//

#import "GPCatalog.h"
#import "AlternateCatalog.h"
#import "AlternateCatalogName.h"
#import "Attachment.h"
#import "BureauPrecancel.h"
#import "Cachet.h"
#import "Cancelations.h"
#import "Country.h"
#import "Format.h"
#import "GPCatalog.h"
#import "GPCatalogGroup.h"
#import "GPCatalogSet.h"
#import "GPPicture.h"
#import "GPSalesGroup.h"
#import "GPSubvarietyType.h"
#import "LooksLike.h"
#import "NumberOfStampsInPlate.h"
#import "PlateNumber.h"
#import "PlateUsage.h"
#import "Stamp.h"
#import "Topic.h"
#import "Valuation.h"


@implementation GPCatalog

@dynamic album_height;
@dynamic album_width;
@dynamic alternate_picture_1;
@dynamic alternate_picture_2;
@dynamic alternate_picture_3;
@dynamic alternate_picture_4;
@dynamic alternate_picture_5;
@dynamic alternate_picture_6;
@dynamic always_display;
@dynamic background_information;
@dynamic color;
@dynamic color_error;
@dynamic color_variety;
@dynamic composite_placeholder;
@dynamic date_documented_first_use;
@dynamic date_documented_first_use_exact;
@dynamic date_issued;
@dynamic date_issued_exact;
@dynamic default_picture;
@dynamic denomination;
@dynamic design_measurement;
@dynamic designers;
@dynamic engravers;
@dynamic envelope_size;
@dynamic gp_catalog_number;
@dynamic gp_description;
@dynamic gum;
@dynamic gum_variety;
@dynamic has_subvarieties;
@dynamic hidden;
@dynamic identification_notes;
@dynamic is_custom;
@dynamic is_default;
@dynamic issue_location;
@dynamic issue_name;
@dynamic knife;
@dynamic long_description;
@dynamic multiple_transfer;
@dynamic number_of_panes;
@dynamic number_of_plates;
@dynamic number_of_plates_used;
@dynamic other_error;
@dynamic pane_size;
@dynamic paper_color;
@dynamic paper_type;
@dynamic perf_error;
@dynamic perforation;
@dynamic perforation_type;
@dynamic plate_block_quantity;
@dynamic plate_error;
@dynamic plate_size;
@dynamic plate_variation;
@dynamic plate_variation_type;
@dynamic plated;
@dynamic press;
@dynamic print;
@dynamic print_variety;
@dynamic printer;
@dynamic printing_on_back;
@dynamic quantity_ordered;
@dynamic quantity_printed;
@dynamic quantity_sold;
@dynamic series;
@dynamic surcharge_type;
@dynamic surcharged;
@dynamic tag;
@dynamic tag_error;
@dynamic tag_variety;
@dynamic variety_description;
@dynamic variety_type;
@dynamic very_rare;
@dynamic watermark;
@dynamic watermark_error;
@dynamic watermark_variation;
@dynamic alternateCatalogs;
@dynamic attachments;
@dynamic bureauPrecancels;
@dynamic cachets;
@dynamic cancelations;
@dynamic catalogGroup;
@dynamic catalogSets;
@dynamic country;
@dynamic defaultCatalogName;
@dynamic examples;
@dynamic extraPictures;
@dynamic formatType;
@dynamic looksLike;
@dynamic majorVariety;
@dynamic numberOfStampsInPlate;
@dynamic plateNumbers;
@dynamic plateUsage;
@dynamic salesGroup;
@dynamic stamps;
@dynamic subvarieties;
@dynamic subvarietyType;
@dynamic topics;
@dynamic values;

@end
